export { Footer } from './Footer'
export { Text } from './Text'
export { InfoContainer } from './InfoContainer'
export { Icon } from './Icon'
export { Link, LinkImportant } from './Links'
export { Spacer } from './Spacer'
export { TextBreaking } from './TextBreaking'
export { PageTitle } from './PageTitle'
export { PageWrapper } from './PageWrapper'
export { Title } from './Title'
